Update testing.yaml

diff --git a/testing.yaml b/testing.yaml
--- a/testing.yaml
+++ b/testing.yaml
@@ -3,7 +3,7 @@ kind: Service
 metadata:
   name: adservice
 spec:
-  type: NodePort
+  type: LoadBalancer
   ports:
   - port: 9555
     targetPort: 9555
@@ -26,7 +26,7 @@ spec:
     spec:
       containers:
       - name: adservice
-        image: delalixx/adservice:latest
+        image: folumii/adservice:latest
         ports:
         - containerPort: 9555
         env:
@@ -42,8 +42,8 @@ metadata:
 spec:
   type: LoadBalancer
   ports:
-  - port: 5050
-    targetPort: 5050
+  - port: 80
+    targetPort: 8080
   selector:
     app: frontend
 ---
@@ -62,10 +62,10 @@ spec:
         app: frontend
     spec:
       containers:
-      - name: adservice
-        image: delalixx/frontend:latest
+      - name: frontend
+        image: folumii/frontend:latest
         ports:
-        - containerPort: 5050
+        - containerPort: 8080
         env:
         - name: MESSAGE
           value: Hello from my first microservices front end deployment!
@@ -79,8 +79,8 @@ metadata:
 spec:
   type: LoadBalancer
   ports:
-  - port: 2020
-    targetPort: 2020
+  - port: 7070
+    targetPort: 7070
   selector:
     app: cartservice
 ---
@@ -99,10 +99,355 @@ spec:
         app: cartservice
     spec:
       containers:
-      - name: adservice
-        image: delalixx/cartservice:latest
+      - name: cartservice
+        image: folumii/cartservice:latest
         ports:
-        - containerPort: 5050
+        - containerPort: 7070
         env:
         - name: MESSAGE
-          value: Hello from my first microservices front end deployment!          
+          value: Hello from my first microservices front end deployment!  
+  #### END of CARTSERVICE ###
+  -----
+  apiVersion: v1
+kind: Service
+metadata:
+  name: checkoutservice
+spec:
+  type: ClusterIP
+  selector:
+    app: checkoutservice
+  ports:
+    port: 5050
+    targetPort: 5050
+  ---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: checkoutservice
+spec:
+  selector:
+    matchLabels:
+      app: checkoutservice
+  template:
+    metadata:
+      labels:
+        app: checkoutservice
+    spec:
+      containers:
+          image: folumii/checkoutservice:latest
+          ports:
+          - containerPort: 5050
+          env:
+          - name: PORT
+            value: "5050"
+          - name: PRODUCT_CATALOG_SERVICE_ADDR
+            value: "productcatalogservice:3550"
+          - name: SHIPPING_SERVICE_ADDR
+            value: "shippingservice:50051"
+          - name: PAYMENT_SERVICE_ADDR
+            value: "paymentservice:50051"
+          - name: EMAIL_SERVICE_ADDR
+            value: "emailservice:5000"
+          - name: CURRENCY_SERVICE_ADDR
+            value: "currencyservice:7000"
+          - name: CART_SERVICE_ADDR
+            value: "cartservice:7070"
+        
+---
+#### END of CHECKOUTERVICE ###
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: currencyservice
+spec:
+  selector:
+    matchLabels:
+      app: currencyservice
+  template:
+    metadata:
+      labels:
+        app: currencyservice
+    spec:
+      containers:
+        image: folumii/checkoutservice:latest
+        ports:
+          containerPort: 7000
+        env:
+        - name: PORT
+          value: "7000"
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: currencyservice
+spec:
+  type: ClusterIP
+  selector:
+    app: currencyservice
+  ports:
+    port: 7000
+    targetPort: 7000
+---
+#### END of CURRENCYSERVICE ###
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: emailservice
+spec:
+  selector:
+    matchLabels:
+      app: emailservice
+  template:
+    metadata:
+      labels:
+        app: emailservice
+    spec:
+      containers:
+        image: folumii/emailservice:latest
+        ports:
+        - containerPort: 8080
+        env:
+        - name: PORT
+          value: "8080"
+        
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: emailservice
+spec:
+  type: ClusterIP
+  selector:
+    app: emailservice
+  ports:
+    port: 5000
+    targetPort: 8080
+    
+ ---
+#### END of EMAILSERVICE ###
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: loadgenerator
+spec:
+  selector:
+    matchLabels:
+      app: loadgenerator
+  replicas: 1
+  template:
+    metadata:
+      labels:
+        app: loadgenerator
+    spec:
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        securityContext:
+        image: busybox:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
+      containers:
+        image: folumii/loadgenerator:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
+     ---
+#### END of LOADGENERATOR ###
+---    
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: paymentservice
+spec:
+  selector:
+    matchLabels:
+      app: paymentservice
+  template:
+    metadata:
+      labels:
+        app: paymentservice
+    spec:
+      containers:
+        image: folumii/paymentservice:latest
+        ports:
+        - containerPort: 50051
+        env:
+        - name: PORT
+          value: "50051"
+          
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: paymentservice
+spec:
+  type: ClusterIP
+  selector:
+    app: paymentservice
+  ports:
+    port: 50051
+    targetPort: 50051
+---
+#### END of PAYMENTSERVICE ###
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: productcatalogservice
+spec:
+  selector:
+    matchLabels:
+      app: productcatalogservice
+  template:
+    metadata:
+      labels:
+        app: productcatalogservice
+    spec:
+      containers:
+        image: folumii/productcatalogservice:latest
+        ports:
+        - containerPort: 3550
+        env:
+        - name: PORT
+          value: "3550"
+        
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: productcatalogservice
+spec:
+  type: ClusterIP
+  selector:
+    app: productcatalogservice
+  ports:
+    port: 3550
+    targetPort: 3550
+---
+#### END of PRODUCTCATALOGUESERVICE ###
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: redis-cart
+spec:
+  selector:
+    matchLabels:
+      app: redis-cart
+  template:
+    metadata:
+      labels:
+        app: redis-cart
+    spec:
+      containers:
+      - name: redis
+        image: redis:alpine
+        ports:
+        - containerPort: 6379
+        volumeMounts:
+        - mountPath: /data
+          name: redis-data
+      volumes:
+      - name: redis-data
+        emptyDir: {}
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: redis-cart
+spec:
+  type: ClusterIP
+  selector:
+    app: redis-cart
+  ports:
+  - name: tcp-redis
+    port: 6379
+    targetPort: 6379
+---
+#### END of REDISDB ###
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: recommendationservice
+spec:
+  selector:
+    matchLabels:
+      app: recommendationservice
+  template:
+    metadata:
+      labels:
+        app: recommendationservice
+    spec:
+      containers:
+        image: folumii/recommendationservice:latest
+        ports:
+        - containerPort: 8080
+        env:
+        - name: PORT
+          value: "8080"
+        - name: PRODUCT_CATALOG_SERVICE_ADDR
+          value: "productcatalogservice:3550"
+        - name: DISABLE_PROFILER
+          value: "1"
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: recommendationservice
+spec:
+  type: ClusterIP
+  selector:
+    app: recommendationservice
+  ports:
+    port: 8080
+    targetPort: 8080
+ ---
+#### END of RECOMMENDATIONSERVICE ###
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: shippingservice
+spec:
+  selector:
+    matchLabels:
+      app: shippingservice
+  template:
+    metadata:
+      labels:
+        app: shippingservice
+    spec:
+      containers:
+        image: folumii/shippingservice:latest
+        ports:
+        - containerPort: 50051
+        env:
+        - name: PORT
+          value: "50051"
+       
+---
+apiVersion: v1
+kind: Service
+metadata:
+  name: shippingservice
+spec:
+  type: ClusterIP
+  selector:
+    app: shippingservice
+  ports:
+    port: 50051
+    targetPort: 50051
